### ISSUE TITLE
configuration

### ISSUE THREAD

**Issue by coledice** [its0x08/wg-install#1]
How do I change SERVER_HOST ? Also, does the setup make client-wg0.conf the server configuration and then the /etc/wireguard/wg0.conf file is the client configuration.  

I appreciate your time and effort.

Thanks,
Cole

**Comment by matrixlord1** [comment]
Same issue. I need change public IP.

**Comment by matrixlord1** [comment]
cd /opt;wget https://bit.ly/2V2oi1N -O wg.sh;chmod +x wg.sh;bash wg.sh
