### ISSUE TITLE
No external internet access when installed on Centos 8

### ISSUE THREAD

**Issue by barryboom** [its0x08/wg-install#10]
Hi just wanted to advise that there is an issue with the setup on Centos 8
i had a clean fully patched install of Centos 8 and script runs perfectly and generates clients and even allows clients to connect just fine but afterwards there appears to be no external gateway so therefore no internet connection for all clients. This occured even after multiple reboots.

i was testing using a number of different routers and levels of firmware on them but mainly a GLinet A750 running 3.104 which fully supports WG clients.

today whilst trying to determine further i rebuilt server to Ubuntu 20.04 ran all upgrades ran the scripts and added it to the same routers as previous test with Centos 8 and all worked fine internet access exactly as expected.

**Comment by its0x08** [comment]
Take a paper and a pencil and draw the schematic of ur LAN please because I really didn't understand anything!

**Comment by barryboom** [comment]
> 
> 
> Take a paper and a pencil and draw the schematic of ur LAN please because I really didn't understand anything!

Hi sorry i have over explained the issue and my logic. To keep it simple the script does not work on Centos 8 there is no external access out from VPS when connected via WG when using the script provided. It works fine on Ubuntu.
