### ISSUE TITLE
the Servers public IP address is always 127.0.1.1, not my VPS ip

### ISSUE THREAD

**Issue by qnyblog** [its0x08/wg-install#11]
Hello, i installed several times, the Servers public IP address is always 127.0.1.1, not my VPS ip

[i] OS:  Ubuntu
[i] Servers public IP address is 127.0.1.1  Is that correct? [y/n]: n
[-] Aborted. Use environment variable SERVER_HOST to set the correct public IP address

**Comment by its0x08** [comment]
Read it one more time carefully!
It says u can use **SERVER_HOST** _envoirment variable_ to declare your **IP** in case its not automatically found!!!

**Comment by qnyblog** [comment]
Thank you very much. the problem is how to use SERVER_HOST envoirment variable to declare my IP.  please kindly help, thank you, have a nice day. (its always can't automatically found VPS ip for me)

**Comment by its0x08** [comment]
Run this `vi ~/.bash_profile` and append something like this `SERVER_HOST=120.34.5.67 `but with your IP instead or run
`$ export SERVER_HOST=120.34.5.67` and then `echo $SERVER_HOST` to check if the variable is set.

**Comment by qnyblog** [comment]
thank you, have a nice day
