### ISSUE TITLE
Support for openwrt ?

### ISSUE THREAD

**Issue by ispire2** [its0x08/wg-install#28]
This is a great script. I have a R7000 nighthawk with freshtomato and support for opkg. Would be great if OpenWRT support could be added.

**Comment by its0x08** [comment]
Hello @ispire2 ,

Very good to hear that.
I'd love to add support for openwrt. It is planned but I can't promise you it will be ready anytime soon!

If anyone from the community is able to help by opening pull requests, they'll be welcome!

Thank you!
