### ISSUE TITLE
One-liners are pointing to a non existing file.

### ISSUE THREAD

**Issue by barryboom** [its0x08/wg-install#29]
git clone https://github.com/its0x08/wg-install.git
cd wg-install
bash wg.sh

is this not missing a CHMOD command to make executable ?

**Comment by barryboom** [comment]
actually think it should be bash wg-install.sh not wg.sh

**Comment by its0x08** [comment]
Correct 👍🏻
Make a pull request with the changes.
Or I'll do it once I'm free...

**Comment by its0x08** [comment]
Hello @barryboom,


It is now fixed by renaming the file.
You can do now a git pull or git clone and try again!

Best regards,
@its0x08
