### ISSUE TITLE
too slow

### ISSUE THREAD

**Issue by broros** [its0x08/wg-install#4]
my internet connection is a bit slower than OpenVPN I had installed previously, and they said WG was supposed to be faster...

looking at other installation guides I think you are missing a few things like install and configure unbound
sudo apt install -y unbound unbound-host

check this file for other things you might be missing...

https://github.com/drew2a/wireguard/blob/master/wg-ububtu-server-up.sh

**Comment by broros** [comment]
dropping pakets

```
wg0: flags=209<UP,POINTOPOINT,RUNNING,NOARP>  mtu 1420
        inet 10.9.0.1  netmask 255.255.255.0  destination 10.9.0.1
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)
        RX packets 93583  bytes 27001616 (25.7 MiB)
        RX errors 0  dropped 106  overruns 0  frame 0
        TX packets 144145  bytes 183915592 (175.3 MiB)
        TX errors 0  dropped 40 overruns 0  carrier 0  collisions 0
```

**Comment by broros** [comment]
still getting  RX errors 19 on a new ubuntu 18 TLS install

**Comment by its0x08** [comment]
> my internet connection is a bit slower than OpenVPN I had installed previously, and they said WG was supposed to be faster...
> 
> looking at other installation guides I think you are missing a few things like install and configure unbound
> sudo apt install -y unbound unbound-host
> 
> check this file for other things you might be missing...
> 
> https://github.com/drew2a/wireguard/blob/master/wg-ububtu-server-up.sh

It
