### ISSUE TITLE
wg.sh: line 176: -4: substring expression < 0

### ISSUE THREAD

**Issue by MohammadHasham** [its0x08/wg-install#8]
OS: Ubuntu

Issue: cannot enter client name.

**Comment by its0x08** [comment]
Can you attach a screenshot?!
Just yesterday used this script to setup 3 Ubuntu servers and 10 clients each.. everything went smooth!
So unless I can see whats wrong with your particular ubuntu I cannot fix anything.
Thank you.

**Comment by MohammadHasham** [comment]
![image](https://user-images.githubusercontent.com/17927649/84826784-eb464a00-b03c-11ea-8e3f-b80140654e0e.png)

I have tried with several other names as well.

**Comment by its0x08** [comment]
Plsease attach the /etc/wireguard/wg0.conf

**Comment by MohammadHasham** [comment]
```[Interface]
Address = 10.0.0.25/32
PrivateKey = <PublicKey>
DNS = 1.1.1.1

[Peer]
PublicKey = <PRIVATE KEY>
Endpoint = 13.71.64.135:51820
AllowedIPs = 0.0.0.0/0
`````

**Comment by its0x08** [comment]
I need the first line only, the one that starts with `#`
you can change the ip to 127.0.0.1 and 192.168.1.1 for privacy reasons..
also dont worry about the key because you will have anyway to regenerate the servers config...
