### ISSUE TITLE
Deleting / removing connections 

### ISSUE THREAD

**Issue by barryboom** [its0x08/wg-install#9]
love the ease of use of the setup with nice and easy commands to install and create and view connection status of clients.

However wondering the cleanest way to remove a connection and return the released local IP back to the pool within the set subnet
meaning its available again to be used for a newly created config.

**Comment by its0x08** [comment]
Im happy that you like the project.
A way to remove a client is on its way and will be added to the script after it passes testing on multiple OS.
This issue will stay open for now.

**Comment by barryboom** [comment]
> 
> 
> Im happy that you like the project.
> A way to remove a client is on its way and will be added to the script after it passes testing on multiple OS.
> This issue will stay open for now.

Thanks very mich for the response and glad to see its in progress, One thing i wish to clarify does this only setup an internal WG VPN connections as after i added a few clients for testing i was able to connect just fine but lost all internet access on all the end points once connected. My setup was centos 8 but scrapped the VPS today and trying different OS's and build to find a soloutoin that still allows an internet passthrough.

Any help would appreciatted i am very knew to linux so could well be my setup and lack of understanding.

**Comment by its0x08** [comment]
On the server side the connections continues to be as before, on the client side it passes all through the VPN tunnel.

**Comment by TheGlockMisc** [comment]
@its0x08 Any Uninstallers?

**Comment by its0x08** [comment]
@TheGlockMisc  just added the uninstaller!
Can you please test it and report any issues?!
